baseURL: 'https://schleyconsult.ch'
languageCode: "de"
title: schley consult.
disableKinds:
  - taxonomy
  - term
  - RSS
  - robotsTXT

theme: business

params:
  copyright: © Schley Consult GmbH
  description: |
    Dr. Frank Schley selbständiger Berater, Interims-Manager oder Verwaltungsrat. Ich führe alle Mandate persönlich aus und berate meine Kunden effizient und resultatorientiert. Solide Fachkompetenz und gute Intuition zeichnen mich aus.
  favicon: images/favicon.png
  images:
    - images/cover-image.jpg
  title: schley consult.
  meta:
    keywords: 'schley consult, consult, consulting, schley, frank schley, management, beratung, madate, selbständiger, Verkehr, Energie, öffentlicher Verkehr, Coporate Governace'
