<?php
/**
 * Decap CMS – GitHub OAuth callback
 *
 * Real PHP file — no .htaccess rewriting needed.
 * GitHub redirects here after the user authorises the OAuth App.
 *
 * Register this URL in the GitHub OAuth App:
 *   https://beta.schley.ch/cms-oauth/callback.php   (staging)
 *   https://schleyconsult.ch/cms-oauth/callback.php  (production)
 */

declare(strict_types=1);

// Prevent COOP from severing the popup↔opener relationship during the OAuth redirect loop.
header('Cross-Origin-Opener-Policy: unsafe-none');

$config = loadConfig();
$code   = $_GET['code']  ?? '';
$state  = $_GET['state'] ?? '';

// Verify self-signed HMAC state — no session required
if (!verifyState($state, $config['client_secret'])) {
    renderError('Ungültiger oder abgelaufener State-Parameter. Bitte erneut anmelden.');
    exit;
}

if ($code === '') {
    renderError('Kein Autorisierungscode von GitHub erhalten.');
    exit;
}

// Exchange code → access token
$response = curlPost('https://github.com/login/oauth/access_token', [
    'client_id'     => $config['client_id'],
    'client_secret' => $config['client_secret'],
    'code'          => $code,
    'redirect_uri'  => callbackUrl(),
], ['Accept: application/json']);

if ($response === false) {
    renderError('Verbindung zu GitHub fehlgeschlagen.');
    exit;
}

$data = json_decode($response, true);

if (empty($data['access_token'])) {
    $detail = $data['error_description'] ?? $data['error'] ?? 'Unbekannter Fehler';
    renderError('Token-Austausch fehlgeschlagen: ' . $detail);
    exit;
}

renderSuccess($data['access_token']);

// ── Helpers ───────────────────────────────────────────────────────────────────

function loadConfig(): array
{
    $path = dirname(dirname($_SERVER['DOCUMENT_ROOT'])) . '/cms_oauth_config.php';
    if (!is_file($path)) {
        http_response_code(500);
        die('OAuth-Konfiguration nicht gefunden: ' . htmlspecialchars($path));
    }
    return require $path;
}

function callbackUrl(): string
{
    $scheme = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    return $scheme . '://' . $host . '/cms-oauth/callback.php';
}

/**
 * Verify the HMAC state token generated by index.php.
 * Valid for 10 minutes; no server-side storage needed.
 */
function verifyState(string $state, string $secret): bool
{
    if ($state === '') return false;
    // Reverse URL-safe base64 (-_ → +/) and restore padding before decoding
    $b64     = strtr($state, '-_', '+/') . str_repeat('=', strlen($state) % 4);
    $decoded = base64_decode($b64, strict: true);
    if ($decoded === false) return false;
    $parts = explode(':', $decoded, 3);
    if (count($parts) !== 3) return false;
    [$ts, $nonce, $sig] = $parts;
    if (time() - (int) $ts > 600) return false;
    return hash_equals(hash_hmac('sha256', $ts . ':' . $nonce, $secret), $sig);
}

function curlPost(string $url, array $fields, array $headers = []): string|false
{
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => http_build_query($fields),
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER     => $headers,
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    $result = curl_exec($ch);
    curl_close($ch);
    return $result;
}

function renderSuccess(string $token): void
{
    $payload = json_encode(json_encode(['token' => $token, 'provider' => 'github']));
    echo <<<HTML
    <!DOCTYPE html>
    <html lang="de">
    <head><meta charset="utf-8"><title>Authentifizierung erfolgreich</title></head>
    <body>
    <p>Authentifizierung erfolgreich. Dieses Fenster wird geschlossen…</p>
    <script>
    (function () {
      var payload = {$payload};

      console.log('[OAuth] opener:', window.opener);

      if (!window.opener) {
        document.querySelector('p').textContent =
          'Fehler: window.opener ist null – Fenster schließen und erneut versuchen.';
        return;
      }

      console.log('[OAuth] → authorizing:github');
      window.opener.postMessage('authorizing:github', '*');

      window.addEventListener('message', function handler(e) {
        console.log('[OAuth] ← message from CMS:', e.data, 'origin:', e.origin);
        window.removeEventListener('message', handler);
        console.log('[OAuth] → sending success token');
        window.opener.postMessage('authorization:github:success:' + payload, e.origin);
      }, false);
    })();
    </script>
    </body>
    </html>
    HTML;
}

function renderError(string $message): void
{
    http_response_code(400);
    $safeMsg = htmlspecialchars($message, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    $jsMsg   = json_encode($message);
    echo <<<HTML
    <!DOCTYPE html>
    <html lang="de">
    <head><meta charset="utf-8"><title>Fehler bei der Authentifizierung</title></head>
    <body>
    <p>Fehler: {$safeMsg}</p>
    <script>
    (function () {
      if (window.opener) {
        window.opener.postMessage('authorization:github:error:' + {$jsMsg}, '*');
      }
    })();
    </script>
    </body>
    </html>
    HTML;
}
