<?php
/**
 * Decap CMS – GitHub OAuth callback
 *
 * Real PHP file — no .htaccess rewriting needed.
 * GitHub redirects here after the user authorises the OAuth App.
 *
 * Register this URL in the GitHub OAuth App:
 *   https://beta.schley.ch/cms-oauth/callback.php   (staging)
 *   https://schleyconsult.ch/cms-oauth/callback.php  (production)
 */

declare(strict_types=1);

// Prevent COOP from severing the popup↔opener relationship during the OAuth redirect loop.
header('Cross-Origin-Opener-Policy: unsafe-none');

$config = loadConfig();
$code   = $_GET['code']  ?? '';
$state  = $_GET['state'] ?? '';

// Verify self-signed HMAC state — no session required
if (!verifyState($state, $config['client_secret'])) {
    renderError('Ungültiger oder abgelaufener State-Parameter. Bitte erneut anmelden.');
    exit;
}

if ($code === '') {
    renderError('Kein Autorisierungscode von GitHub erhalten.');
    exit;
}

// Exchange code → access token
$response = curlPost('https://github.com/login/oauth/access_token', [
    'client_id'     => $config['client_id'],
    'client_secret' => $config['client_secret'],
    'code'          => $code,
    'redirect_uri'  => callbackUrl(),
], ['Accept: application/json']);

if ($response === false) {
    renderError('Verbindung zu GitHub fehlgeschlagen.');
    exit;
}

$data = json_decode($response, true);

if (empty($data['access_token'])) {
    $detail = $data['error_description'] ?? $data['error'] ?? 'Unbekannter Fehler';
    renderError('Token-Austausch fehlgeschlagen: ' . $detail);
    exit;
}

renderSuccess($data['access_token']);

// ── Helpers ───────────────────────────────────────────────────────────────────

function loadConfig(): array
{
    $path = dirname(dirname($_SERVER['DOCUMENT_ROOT'])) . '/cms_oauth_config.php';
    if (!is_file($path)) {
        http_response_code(500);
        die('OAuth-Konfiguration nicht gefunden: ' . htmlspecialchars($path));
    }
    return require $path;
}

function callbackUrl(): string
{
    $scheme = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    return $scheme . '://' . $host . '/cms-oauth/callback.php';
}

/**
 * Verify the HMAC state token generated by index.php.
 * Valid for 10 minutes; no server-side storage needed.
 */
function verifyState(string $state, string $secret): bool
{
    if ($state === '') return false;
    // Reverse URL-safe base64 (-_ → +/) and restore padding before decoding
    $b64     = strtr($state, '-_', '+/') . str_repeat('=', strlen($state) % 4);
    $decoded = base64_decode($b64, strict: true);
    if ($decoded === false) return false;
    $parts = explode(':', $decoded, 3);
    if (count($parts) !== 3) return false;
    [$ts, $nonce, $sig] = $parts;
    if (time() - (int) $ts > 600) return false;
    return hash_equals(hash_hmac('sha256', $ts . ':' . $nonce, $secret), $sig);
}

function curlPost(string $url, array $fields, array $headers = []): string|false
{
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => http_build_query($fields),
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER     => $headers,
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    $result = curl_exec($ch);
    curl_close($ch);
    return $result;
}

function renderSuccess(string $token): void
{
    // json_encode produces a safe JS string literal (handles quotes, backslashes, etc.)
    $token_js = json_encode($token);
    echo <<<HTML
    <!DOCTYPE html>
    <html lang="de">
    <head><meta charset="utf-8"><title>Authentifizierung erfolgreich</title></head>
    <body>
    <p style="font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:24px;color:#1f2430;">Anmeldung wird abgeschlossen…</p>
    <script>
    (function () {
      var token    = {$token_js};
      var provider = 'github';
      var payload  = JSON.stringify({ token: token, provider: provider });

      console.log('[OAuth] opener:', window.opener);

      if (!window.opener) {
        document.querySelector('p').textContent =
          'Fehler: window.opener ist null – Fenster schließen und erneut versuchen.';
        return;
      }

      // Decap CMS handshake (mit Safari-Härtung):
      //  1. Popup sendet  'authorizing:github'  → CMS  (wiederholt – Safari
      //     verwirft einzelne postMessages nach dem GitHub-Umweg gerne mal)
      //  2. CMS antwortet 'authorizing:github'  → Popup
      //  3. Popup sendet  'authorization:github:success:…' → CMS
      // Fallback: Bleibt die CMS-Antwort aus (Safari blockiert die Rückrichtung),
      // senden wir das Token direkt. Der CMS hat seinen Success-Listener bereits
      // registriert, sobald er EINE 'authorizing'-Nachricht gesehen hat.

      var done = false;

      function finish(origin) {
        if (done) return;
        done = true;
        window.opener.postMessage('authorization:' + provider + ':success:' + payload, origin || '*');

        // Erfolg anzeigen, dann schließen. Safari verweigert window.close() bei
        // Popups mit Verlauf – dann bleibt das Fenster mit diesem Hinweis offen.
        document.querySelector('p').textContent =
          '✓ Anmeldung erfolgreich. Sie können dieses Fenster jetzt schließen.';
        setTimeout(function () { window.close(); }, 300);
      }

      // Schritt 1+3: auf die CMS-Antwort warten, dann Token senden
      window.addEventListener('message', function receiveMessage(event) {
        if (event.source !== window.opener || done) return;
        window.removeEventListener('message', receiveMessage);
        console.log('[OAuth] CMS replied, origin:', event.origin, '– sending token');
        finish(event.origin);
      }, false);

      // Schritt 2: 'authorizing' senden – mehrfach, falls Safari die erste
      // Nachricht verschluckt. Nach ~4 s ohne Antwort: Token direkt senden.
      var tries = 0;
      (function ping() {
        if (done) return;
        if (tries++ > 16) {
          console.log('[OAuth] keine Antwort – sende Token direkt');
          finish('*');
          return;
        }
        console.log('[OAuth] → authorizing:github (' + tries + ')');
        window.opener.postMessage('authorizing:' + provider, '*');
        setTimeout(ping, 250);
      })();
    })();
    </script>
    </body>
    </html>
    HTML;
}

function renderError(string $message): void
{
    http_response_code(400);
    $safeMsg = htmlspecialchars($message, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    $jsMsg   = json_encode($message);
    echo <<<HTML
    <!DOCTYPE html>
    <html lang="de">
    <head><meta charset="utf-8"><title>Fehler bei der Authentifizierung</title></head>
    <body>
    <p>Fehler: {$safeMsg}</p>
    <script>
    (function () {
      if (window.opener) {
        window.opener.postMessage('authorization:github:error:' + {$jsMsg}, '*');
      }
    })();
    </script>
    </body>
    </html>
    HTML;
}
