backend:
  name: github
  repo: oujonny/schley.ch
  branch: development
  base_url: https://beta.schley.ch
  auth_endpoint: cms-oauth/auth

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"
locale: 'de'

collections:
  - name: homepage
    label: "Homepage"
    files:
      - label: "Landing Page"
        name: landing_page
        file: "content/_index.md"
        fields:
          - {label: "Hauptzeile", name: header_headline, widget: string}
          - {label: "Unterzeile", name: header_subheadline, widget: string}
          - {label: "Hintergrundbild", name: header_image, widget: image}
      - label: "Portrait"
        name: portrait_index
        file: "content/homepage/portrait/_index.md"
        fields:
          - { label: "Inhalt", name: body, widget: markdown }
          - { label: "Bild", name: page_image, widget: object, fields: [
              { label: "Bilddatei", name: src, widget: image, media_folder: "content/homepage/portrait", public_folder: "" }
            ]}
      - label: "Slogan"
        name: slogan
        file: "content/homepage/slogan.md"
        fields:
          - {label: "Inhalt", name: body, widget: markdown}
      - label: "Mein Versprechen"
        name: versprechen
        file: "content/homepage/mein_versprechen.md"
        fields:
          - { label: "Titel", name: title, widget: string }
          - { label: "Inhalt", name: body, widget: markdown }
      - label: "Kontakt"
        name: kontakt
        file: "content/homepage/kontakt/_index.md"
        fields:
          - { label: "Titel", name: title, widget: string }
          - { label: "Inhalt", name: body, widget: markdown }
          - { label: "Bild", name: page_image, widget: object, fields: [
              { label: "Bilddatei", name: src, widget: image, media_folder: "content/homepage/kontakt", public_folder: "" }
            ]}

  - name: angebot
    label: "Angebot"
    folder: "content/homepage/angebot"
    create: true
    fields:
      - { label: "Titel", name: title, widget: string }
      - { label: "Inhalt", name: body, widget: markdown }

  - name: ueber_mich
    label: "Über mich"
    files:
      - label: "Berufliche Stationen"
        name: berufliche_stationen
        file: "content/homepage/ueber_mich/berufliche_stationen.md"
        fields:
          - {label: "Titel", name: title, widget: string}
          - {label: "Inhalt", name: body, widget: markdown}

      - label: "Mandate & Aktivitäten"
        name: mandate_aktivitaeten
        file: "content/homepage/ueber_mich/mandate_aktivitaeten.md"
        fields:
          - {label: "Titel", name: title, widget: string}
          - {label: "Inhalt", name: body, widget: markdown}

  - name: referenzbeispiele
    label: "Referenzbeispiele"
    folder: "content/homepage/ueber_mich/referenzbeispiele"
    create: true
    fields:
      - { label: "Titel", name: title, widget: string }
      - { label: "Inhalt", name: body, widget: markdown }

  - name: referenzen
    label: "Referenzen / Zitate"
    folder: "content/homepage/referenzen"
    create: true
    fields:
      - {label: "Name", name: title, widget: string}
      - {label: "Reihenfolge", name: weight, widget: number, default: 10}
      - {label: "Zitat und Position", name: body, widget: markdown}

  - name: seiten
    label: "Statische Seiten"
    files:
      - label: "Ausbildungen"
        name: ausbildungen
        file: "content/homepage/portrait/ausbildungen.md"
        fields:
          - { label: "Titel", name: title, widget: string }
          - { label: "Inhalt", name: body, widget: markdown }
      - label: "Impressum"
        name: impressum
        file: "content/impressum.md"
        fields:
          - {label: "Inhalt", name: body, widget: markdown}

      - label: "Datenschutz"
        name: datenschutz
        file: "content/datenschutz.md"
        fields:
          - {label: "Inhalt", name: body, widget: markdown}

      - label: "Kooperationspartner"
        name: kooperationspartner
        file: "content/kooperationspartner.md"
        fields:
          - {label: "Titel", name: title, widget: string}
          - {label: "Inhalt", name: body, widget: markdown}
